# Generated by Django 6.0.2 on 2026-05-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='address_line1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='admission',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='admission',
            name='caste',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='father_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='admission',
            name='father_occupation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='admission',
            name='height',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='admission',
            name='language',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('unmarried', 'Unmarried'), ('married', 'Married')], default='unmarried', max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='admission',
            name='mother_occupation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='admission',
            name='nationality',
            field=models.CharField(default='Indian', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='pincode',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='admission',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=10),
        ),
        migrations.AddField(
            model_name='admission',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
